name: Publish Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WORKLOAD_NAME: 'bicep-petname'
  
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bicep
        run: az bicep install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Bicep Module
        run: |
          MODULE_NAME="bicep-petname"
          MODULE_VERSION="1.0.0"

          az bicep publish \
            --file petname.bicep \
            --target br:ghcr.io/rbby/bicep-petname:1.0.0
            
          # az bicep publish \
          #   --file ./petname.bicep \
          #   --target ghcr.io/${{ github.repository_owner }}/bicep-modules/petname:${MODULE_VERSION}



  
        
