name: Publish Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WORKLOAD_NAME: 'bicep-petname'

jobs:
  publish-module:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy package to GitHub Container Registry
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            set -ex
            az --version
            TEMPLATE_FILE_PATH="./deployment/module-template-spec.bicep"

            az bicep build $TEMPLATE_FILE_PATH --outdir ./deployment/compiled
            COMPILED_TEMPLATE_FILE_PATH="./deployment/compiled/module-template-spec.json"

            az stack sub create  \
              --name petname-stack \
              --template-file $COMPILED_TEMPLATE_FILE_PATH \
              --location germanywestcentral \
              --description "Stack for deploying the bicep petname module template spec" \
              --deny-settings-mode None \
              --action-on-unmanage detachAll
